### ISSUE TITLE
Create namespaces from templates or reuse existing ones

### ISSUE THREAD

**Issue by johnqa** [cloud-bulldozer/kube-burner#115]
Hi,

I am trying to find a way to run kube-burner tests in a RKE cluster, where there is a gatekeeper that only allows the creation of namespaces if they have certain labels and annotations.

I tried to create upfront the namespace and then run the tests but that did not worked.

Is there a way to add metadata to namespaces created by kube-burner or to have the tool reuse the existing ones?

Thank you!

**Comment by johnqa** [comment]
Hi,

So I have the following section in cfg file:
```
jobs:
- name: kube-burner-job
  jobType: create
  jobIterations: 2
  qps: 20
  burst: 40
  namespacedIterations: false
  cleanup: true
  namespace: kube-burner-job-ns
  podWait: false
  waitWhenFinished: true
  waitFor: ["Deployment"]
  verifyObjects: true
  errorOnVerify: false
  jobIterationDelay: 0s
  jobPause: 1s
objects:
  - objectTemplate: /tmp/burner/objectTemplates/svc.yml
      replicas: 1 
  - objectTemplate: /tmp/burner/objectTemplates/deployment.yml
      replicas: 10
      inputVars:
      containerPort: 8081
```

And the error is:
```
time="2022-02-22 09:11:54" level=info msg="Running job kube-burner-job"
time="2022-02-22 09:11:54" level=error msg="Unexpected error creating namespace kube-burner-job-ns: admission webhook \"validation.gatekeeper.sh\" denied the request: [denied by projectidrequired] you must provide annotations: {\"field.cattle.io/projectId\"}\n[denied by projectidrequired] you must provide labels: {\"field/owner\", \"field/solution\"}"
time="2022-02-22 09:11:55" level=error msg="Unexpected error creating namespace kube-burner-job-ns: admission webhook \"validation.gatekeeper.sh\" denied the request: [denied by projectidrequired] you must provide annotations: {\"field.cattle.io/projectId\"}\n[denied by projectidrequired] you must provide labels: {\"field/owner\", \"field/solution\"}"
time="2022-02-22 09:11:58" level=error msg="Unexpected error creating namespace kube-burner-job-ns: admission webhook \"validation.gatekeeper.sh\" denied the request: [denied by projectidrequired] you must provide annotations: {\"field.cattle.io/projectId\"}\n[denied by projectidrequired] you must provide labels: {\"field/owner\", \"field/solution\"}"
time="2022-02-22 09:11:58" level=fatal msg="timed out waiting for the condition"
```
My execution is:
```
docker run --rm --user $(id -u):$(id -g) -e KUBECONFIG=/tmp/burner/kubeconfig.yaml -v /home/user/testing/output/results/$(Build.BuildNumber):/tmp/burner cloud-bulldozer/kube-burner init --config /tmp/burner/cfg.yml --uuid $(uuidgen)
```
Thank you for having a look,
John
