### ISSUE TITLE
[BUG] Environment variables are not evaluated when jobs are templated using a sequence

### ISSUE THREAD

**Issue by smalleni** [cloud-bulldozer/kube-burner#134]
**Output of `kube-burner `version**

[smalleni@localhost web-burner]$ kube-burner version
Version: 0.14
Git Commit: c7dee26312c2455b94b95508cb8ecf6c1c91802e
Build Date: 2021-09-30T19:37:03Z
Go Version: go1.16.8
OS/Arch: linux amd64

**Describe the bug**
When environment variables are referenced in the kube-burner config, if the job itself is templated out using a sequence, the environment variables for the job parameters are not evaluated properly.

**To Reproduce**
1. export iter, scale, QPS and BURST on the env
2. Run kube-burner with this config
```
{{ $normalLimit := multiply 1 .scale }}
{{ range $index, $val := sequence 1 $normalLimit }}
  - name: job-{{ $val }}
    jobType: create
    jobIterations: {{ .iter }}
    qps: {{ .QPS }}
    burst: {{ .BURST }}
    namespacedIterations: false
    cleanup: false
    namespace: normal-ns-{{ $val }}
    podWait: false
    waitWhenFinished: false
    waitFor: ["Pod"]
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 20s
    jobPause: 20s
    objects:
      - objectTemplate: objectTemplates/cluster_density_configmap.yml
        replicas: 30
      - objectTemplate: objectTemplates/cluster_density_secret.yml
        replicas: 38
      - objectTemplate: objectTemplates/node_density_pod_served.yml
        replicas: 38
      - objectTemplate: objectTemplates/node_density_pod_service_served.yml
        replicas: 38
      - objectTemplate: objectTemplates/cluster_density_dep_served.yml
        replicas: 5
{{ end }}
```

**Expected behavior**
The environment variables should work within the sequence

**Screenshots or output**
```
INFO[2021-10-14 11:55:39] 🔥 Starting kube-burner (0.14@c7dee26312c2455b94b95508cb8ecf6c1c91802e) with UUID a8d4ac36-193a-431e-856c-0fbe08c72c27 
FATA[2021-10-14 11:55:39] Error rendering configuration template: rendering error: template: :21:22: executing "" at <.iter>: can't evaluate field iter in type int 
```
**Additional context**

**Comment by rsevilla87** [comment]
Hey @smalleni, this is not actually a kube-burner issue. It's related with how golang template language works. When you try to access a varible from within a range loop, the scope changes and then you need to reference "root" variables by prefixing them with a $.
i.e

```yaml
{{ $normalLimit := multiply 1 .scale }}
{{ range $index, $val := sequence 1 $normalLimit }}
  - name: job-{{ $val }}
    jobType: create
    jobIterations: {{ $.iter }}
    qps: {{ $.QPS }}
    burst: {{ $.BURST }}
    namespacedIterations: false
    cleanup: false
    namespace: normal-ns-{{ $val }}
    podWait: false
    waitWhenFinished: false
    waitFor: ["Pod"]
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 20s
    jobPause: 20s
    objects:
      - objectTemplate: objectTemplates/cluster_density_configmap.yml
        replicas: 30
      - objectTemplate: objectTemplates/cluster_density_secret.yml
        replicas: 38
      - objectTemplate: objectTemplates/node_density_pod_served.yml
        replicas: 38
      - objectTemplate: objectTemplates/node_density_pod_service_served.yml
        replicas: 38
      - objectTemplate: objectTemplates/cluster_density_dep_served.yml
        replicas: 5
{{ end }}
```
