### ISSUE TITLE
[RFE] Standalone measure subcommand

### ISSUE THREAD

**Issue by rsevilla87** [cloud-bulldozer/kube-burner#138]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a measure subcommand to make kube-burner able to execute measurements (The current available are podLatency and pprof) without actually running a benchmark

**Describe the solution you'd like**
Adding a new measure subcommand to do something like:

```
kube-burner measure -c configFile --for 1h
```

This new feature will read the kube-burner configuration as usual and then execute the measurements defined there for the time defined by the flag "--for"

**Comment by smalleni** [comment]
@rsevilla87 @shashank-boyapally I thought the purpose of this command is to setup measurements for the next time interval and not grab measurements from the past. The way I am guessing this would be used is to just run kube-burner measurements on a customer's environment for the next 1 hour or so to identify the podready latency etc.

**Comment by vishnuchalla** [comment]
Currently, kube-burner listens to the pod creation event and sets a creation timestamp in our program memory using `time.Now().UTC()` (instead of us manually setting this we can also fetch the exact pod `creationTimestamp` using client-go library) and keeps on looking for the update events and captures each of these timestamps while the each stage gets updated until a pod gets to `Ready` state.
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-07-15T23:45:46Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-07-17T19:27:07Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-07-17T19:27:07Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-07-15T23:45:46Z"
    status: "True"
    type: PodScheduled

``` 
once it has all those timestamps then it calculates latencies for each step. This is while the workload is running. Now that we know how these times are being fetched, we can make tweaks in our current code to capture them for previously ran pods or currently running pods as they transition stages over time.

So instead of an option like `-for 1h`, which I believe is for the future runs, we can have options like `--start_time and --end_time` to get these metrics for a workload which was ran with in that time range, which will also help us to run measurements on previously ran workloads as well as long as their pods are present and also isolates this measurement calculation from a workload run.
