### ISSUE TITLE
Unable to create the storage class resource from kube burner

### ISSUE THREAD

**Issue by Madhan-SWE** [cloud-bulldozer/kube-burner#143]
I am trying to create storage class resource using Kube-burner.
Below is the  job item
```
- name: api-intensive-sc-create
    jobIterations: 1
    qps: 4
    burst: 4
    jobType: create
    namespacedIterations: false
    namespace: kube-system
    podWait: true
    cleanup: true
    waitFor: []
    waitWhenFinished: true
    objects:
      - objectTemplate: templates2/sc.yaml
 ```

**sc.yaml**
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: powervs-sc
provisioner: my.csi.driver.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: tier3
  csi.storage.k8s.io/fstype: xfs
```

But the creation fails with the error:
```
WARN[2021-12-03 04:19:23] Namespace kube-system already exists         
ERRO[2021-12-03 04:19:23] Error creating object StorageClass/powervs-sc in namespace kube-system: the server could not find the requested resource 
ERRO[2021-12-03 04:19:23] Retrying object creation  
```

Storage class is basically a non namespaced resource.
It can  be created only once and used across all jobs and iterations.

Still, I feel creating storage class from Kube-burner will be really helpful.
