### ISSUE TITLE
How to index a tarball to Elasticsearch

### ISSUE THREAD

**Issue by miiraheart** [cloud-bulldozer/kube-burner#159]
**Output of `kube-burner `version**
```
Version: 0.14.3
Git Commit: e8c3b246ac1c9dd52936f55e9b0b76d35d6eca32
Build Date: 2021-12-13T19:07:06Z
Go Version: go1.16.11
OS/Arch: linux amd64
```
**Describe the bug**
Cannot seem to index a tarball to OpenShift Elasticsearch.
**To Reproduce**
`kube-burner init -c api-intensive.yml  -u ${prom_url} -t ${token} -m ../../metrics-profiles/metrics.yaml
`
then: 
```
kube-burner index -c api-intensive.yml  -u ${prom_url} -t ${token} -m ../../metrics-profiles/metrics.yaml
....
INFO[2022-10-01 10:54:39] Writing to: collected-metrics/clusterVersion-42f4b00a-8086-4101-8273-cda23a70e4de.json 
INFO[2022-10-01 10:54:40] Metrics tarball generated at kube-burner-metrics-1643712879.tgz 
```
```
kube-burner import -c api-intensive.yml --tarball kube-burner-metrics-1643712879.tgz
INFO [2022-02-01 11:18:19] Création de l'indexeur : elastic                  
FATA[2022-02-01 11:18:19] Code d'état ES inattendu : 500        
```
I can access ES with a token : 
```
sh-4.4# routeES=`oc get route elasticsearch -o jsonpath={.spec.host}`--nopenshift--logging 
sh-4.4# token=$(oc whoami -t)
sh-4.4# curl -tlsv1.2 --insecure -H "Authorization: Bearer ${token}" "[https://${routeES}](https://%24%7Broutees%7D/)"
{
"name" : "elasticsearch-cdm-XXXXX-1",
"cluster_name" : "elasticsearch",
"cluster_uuid" : "XXX-ID-XXX",
"version" : {
"number" : "6.8.1",
"build_flavor" : "oss",
"build_type" : "zip",
"build_hash" : "Unknown",
"build_date" : "Unknown",
"build_snapshot" : true,
"lucene_version" : "7.7.0",
"minimum_wire_compatibility_version" : "5.6.0",
"minimum_index_compatibility_version" : "5.0.0"
    },
    "tagline" : "You Know, for Search"
  }
```
```
 cat api-intensive.yml
---
global:
  writeToFile: true
  createTarball: true
  metricsDirectory: collected-metrics
  indexerConfig:
    enabled: true
    esServers: [https://elasticsearch-openshift-logging.apps.domain.com]
    defaultIndex: kube-burner
    type: elastic
    insecureSkipVerify: true
....
(rest remains as the example in the Git)

```
**Expected behavior**
I can import the tarball and index it in Elasticsearch (maybe the config yml file includes a field for using a token in the authentication)
