### ISSUE TITLE
[BUG] Unable to create a NetworkAttachmentDefinition resource from kube burner

### ISSUE THREAD

**Issue by josecastillolema** [cloud-bulldozer/kube-burner#324]
I am trying to create a **NetworkAttachmentDefinition** resource using Kube-burner.
Below is the job item:
```
  - name: create-networks-job
    jobType: create
    jobIterations: 1
    qps: 10
    burst: 10
    namespacedIterations: true
    cleanup: false
    namespace: serving-ns
    podWait: false
    waitWhenFinished: false
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 1s
    jobPause: 0s
    preLoadImages: false
    objects:
      - objectTemplate: objectTemplates/macvlan_network.yml
        replicas: 1
```

```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net
  namespace: serving-ns-1
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "internal-net",
      "plugins": [
        {
          "type": "macvlan",
          "master": "breth0",
          "mode": "bridge",
          "ipam": {
            "type": "static"
          }
        },
        {
          "capabilities": {
            "mac": true,
            "ips": true
          },
          "type": "tuning"
        }
      ]
    }
```

But the creation fails with the error:
```
ERRO[2023-05-23 18:09:28] Error creating object NetworkAttachmentDefinition/sriov-net-1 in namespace serving-ns-1: the server could not find the requested resource 
```

Manually creating the resource works, i.e.: `kubectl apply -f macvlan_network.yml`

Kube-burner version 1.6 (tested 1.3 as well).
