### ISSUE TITLE
[BUG] waitOptions.forCondition is a noop on globally scoped objects

### ISSUE THREAD

**Issue by darkmuggle** [cloud-bulldozer/kube-burner#337]
# Bug Description

## **Output of `kube-burner` version**

Version: 1.6
Git Commit: 8265762de894f1bdf28f6488fb2dfeb03debb4dc
Build Date: 2023-05-17T13:37:00Z
Go Version: go1.19.9
OS/Arch: darwin arm64

## **Describe the bug**

`waitOptions` for globally scoped (no namespace) object is a noop. 

## **To Reproduce**

Create a globally scoped object, such as a CRD in test yaml.
Set:
```yaml
global:
  indexerConfig:
    enabled: true
    type: local
    metricsDirectory: /tmp/dump

jobs:
  - name: create-controlplanes
    jobIterations: 1
    qps: 5
    burst: 10
    namespacedIterations: false
    namespace: testing
    preLoadImages: false
    podWait: true
    waitWhenFinished: true
    maxWaitTimeout: 15m
    objects:
      - objectTemplate: resource.yaml
        namespaced: false
        replicas: 1
        wait: true
        waitOptions:
          forCondition: Ready
```

## **Expected behavior**

`waitOptions.forCondition` should work with global scoped resources.

## **Screenshots or output**

Output is: 
```
time="2023-06-02 14:30:02" level=info msg="📁 Creating indexer: local" file="metrics.go:39"
time="2023-06-02 14:30:02" level=info msg="🔥 Starting kube-burner (latest@ed1df612650b3398ab70c4f76cd3514db87c03b4) with UUID 2f66e597-5865-476f-bcd6-3df322d73a7b" file="job.go:82"
time="2023-06-02 14:30:02" level=info msg="📈 Creating measurement factory" file="factory.go:52"
time="2023-06-02 14:30:02" level=info msg="Job create-controlplanes: 1 iterations with 1 ControlPlane replicas" file="create.go:89"
time="2023-06-02 14:30:02" level=info msg="QPS: 5" file="job.go:92"
time="2023-06-02 14:30:02" level=info msg="Burst: 10" file="job.go:93"
time="2023-06-02 14:30:02" level=info msg="Triggering job: create-controlplanes" file="job.go:108"
time="2023-06-02 14:30:02" level=info msg="Deleting namespaces with label kube-burner-job=create-controlplanes" file="namespaces.go:61"
time="2023-06-02 14:30:02" level=info msg="Waiting for namespaces to be definitely deleted" file="namespaces.go:79"
time="2023-06-02 14:30:08" level=info msg="Running job create-controlplanes" file="create.go:104"
time="2023-06-02 14:30:08" level=info msg="0/1 iterations completed" file="create.go:121"
time="2023-06-02 14:30:08" level=info msg="Waiting up to 15m0s for actions to be completed in namespace testing" file="create.go:140"
time="2023-06-02 14:30:08" level=info msg="Actions in namespace default completed" file="waiters.go:75"
time="2023-06-02 14:30:08" level=info msg="Verifying created objects" file="utils.go:64"
time="2023-06-02 14:30:08" level=info msg="controlplanes found: 1 Expected: 1" file="utils.go:97"
time="2023-06-02 14:30:08" level=info msg="Job create-controlplanes took 6s" file="job.go:158"
time="2023-06-02 14:30:08" level=info msg="Indexing metric jobSummary" file="metadata.go:52"
time="2023-06-02 14:30:08" level=info file="metadata.go:58"
time="2023-06-02 14:30:08" level=info msg="Finished execution with UUID: 2f66e597-5865-476f-bcd6-3df322d73a7b" file="job.go:190"
time="2023-06-02 14:30:08" level=info msg="👋 Exiting kube-burner 2f66e597-5865-476f-bcd6-3df322d73a7b" file="kube-burner.go:97"
```
