### ISSUE TITLE
[RFE] kube-burner audit execution 

### ISSUE THREAD

**Issue by jtaleric** [cloud-bulldozer/kube-burner#439]
**Is your feature request related to a problem? Please describe.**
Sort of... 

We need kube-burner to help users understand if their run was "valid". We now have 2 different latency values (v1, v2)... However we also spit out a log message if the latency value is less than zero. 

**Describe the solution you'd like**
If we run 1000 iterations, and 500 of the latency values we retrieve are less than zero (which kube-burner will set zero), we should have kube-burner spit out a message stating that the values captured during the run are unreliable and not meaningful. This could indicate an environmental problem

**Comment by rsevilla87** [comment]
Values less than 0 shouldn't been printed anymore

**Comment by jtaleric** [comment]
> Values less than 0 shouldn't been printed anymore

Along with not printing, we should also not have those zeros calculated in the latency.

**Comment by vishnuchalla** [comment]
Cisco's run full log: [nd-200-ocp4.10.txt](https://github.com/cloud-bulldozer/kube-burner/files/12389975/nd-200-ocp4.10.txt)
Yes fortunately those were just trace logs till now. Attached is a case study in cisco environment, where there was no proper ntp sync or some setup issue on their system under test. And here is an example instance where a pod has very unrealistic times recorded, and the same happened with many in the environment.
```
  creationTimestamp: "2023-08-17T00:56:37Z"
  status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-08-17T00:56:30Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-08-17T00:56:35Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-08-17T00:56:35Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-08-17T00:56:36Z"
    status: "True"
    type: PodScheduled
```
Full describe log of the pod: [pod-describe-and-yaml-output.txt](https://github.com/cloud-bulldozer/kube-burner/files/12389985/pod-describe-and-yaml-output.txt)

### Summary: 
V1 reported 0.74% of them as negative latencies, which is wrong due to extra round-trip time being added by the `client-go` watcher events and `time.now()` set in our code. (i.e. 19788/26716)
V2 reported 0.35% of them as negative latencies, which was exact same number of pods that contain error in their system. (i.e. 9414/26716)
And V1 latencies had atleast >=2s error with the actual timestamps in almost every instance (please search for `Difference between V1 and V2` text in the attached full log for more info) which indicates V1 would report wrong latencies even if their SUT was perfect.

So, as a solution we should run an audit using V2 latencies (as V1 latencies are unreliable due the error added by the `client-go` api round trip times), and report a log indicating our confidence on the results. Based on the fact that, those negative latencies should never occur in real-time, i.e (all life cycle stages timestamps including `Scheduled`, `Initialized`, `ContainersReady` & `PodReady` should always be >= `CreationTimeStamp`) We should have threshold based on V2 latencies, for example if `15%` of the latencies are falling under negative cases, we should log our confidence level for user's understading as it is completely on their SUT. As usual, I am open to other thoughts too and for deciding a `%` value on the threshold.
