### ISSUE TITLE
Avoid using external commands like oc

### ISSUE THREAD

**Issue by rsevilla87** [cloud-bulldozer/kube-burner#470]
We shouldn't use run external commands like `oc` from kube-burner. These objects can be created either by a ClientSet or they can also be part of the workload

https://github.com/cloud-bulldozer/kube-burner/blob/1656082637deadcb6c9b93d68574f3530c28ea0a/pkg/workloads/networkpolicy.go#L38-L49

i.e:
```yaml
jobs:
  - name: createStuff
    objects:
      - objectTemplate: clusterrole.yml
        replicas:1
     - objectTemplate: clusterrolebinding.yml
        replicas: 1

  - name: networkpolicy-matchexpressions
    namespace: networkpolicy-matchexpressions
    jobIterations: {{.JOB_ITERATIONS}}
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: true
    podWait: false
    waitWhenFinished: true
    preLoadImages: true
    preLoadPeriod: 15s
    churn: {{.CHURN}}
    churnDuration: {{.CHURN_DURATION}}
    churnPercent: {{.CHURN_PERCENT}}
    churnDelay: {{.CHURN_DELAY}}
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged

    objects:
      - objectTemplate: deny-all.yml
        replicas: 1

      - objectTemplate: matchexpressions-networkpolicy.yml
        replicas: 5
        inputVars:
          podselector_label_num: "label1"
          podselector_label: "foo"
          ingress_label_num: "label1"
          ingress_label: "foo"

      - objectTemplate: matchexpressions-networkpolicy.yml
        replicas: 5
        inputVars:
          podselector_label_num: "label2"
          podselector_label: "bar"
          ingress_label_num: "label2"
          ingress_label: "bar"

      - objectTemplate: scraper.yml
        replicas: 5
        inputVars:
          label1: "foo"
          label2: "bar"
          workload: "networkpolicy-matchexpressions"
          es_server: "{{.ES_SERVER}}"
          es_index: "networkpolicy-enforcement"
          set: "1"

      - objectTemplate: scraper.yml
etc
 ```
