### ISSUE TITLE
Empty namespaces are left [BUG]

### ISSUE THREAD

**Issue by Muscule** [cloud-bulldozer/kube-burner#91]
**Output of `kube-burner `version**
0.10

**Describe the bug**
After launching kube-burber to create and delete several namespaces and pods, empty namespaces continue to exist in cluster.

**To Reproduce**
1. input 10 namespaces and pods creation and deletion in cfg.yml
2. kube-burner init -c cfg.yml ...
3. empty namespaces created by kube-burner exist in cluster

**Expected behavior**
No empty kube-burner namespaces exist in cluster

**Screenshots or output**

**Additional context**

**Comment by rsevilla87** [comment]
Hey @Muscule, this behaviour is expected with the current implementation. Let's say you have a job like this one

```yaml
...
  - name: delete-job
    jobType: delete
    waitForDeletion: true
    qps: 10
    burst: 20
    objects:

    - kind: Deployment
      labelSelector: {kube-burner-job: kube-burner-job}
      apiVersion: apps/v1
```

The previous job will only remove deployments labeled with kube-burner-job=kube-burner-job, and does nothing with the namespaces where those deployments are. In case you also want to remove the parent namespaces, you need add those resources to the objects list in the config:
```yaml
...
  - name: delete-job
    jobType: delete
    waitForDeletion: true
    qps: 10
    burst: 20
    objects:

    - kind: Deployment
      labelSelector: {kube-burner-job: kube-burner-job}
      apiVersion: apps/v1

    - kind: Namespaces
      labelSelector: {kube-burner-job: kube-burner-job}
```
